services:
  kafka:
    image: apache/kafka-native:3.8.0
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093,EXTERNAL://localhost:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 10
    networks:
      - service

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8088:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: Kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - service

  packages_db:
    image: postgres:17.1
    container_name: packages_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: packages_db
    ports:
      - "5432:5432"
    volumes:
      - packages_data:/var/lib/postgresql/data
    networks:
      - service
    
  billing_db:
    image: postgres:17.1
    container_name: billing_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: billing_db
    ports:
      - "5433:5432"
    volumes:
      - billing_data:/var/lib/postgresql/data
    networks:
      - service

  package-service:
    build:
      context: ./package-service
    restart: always
    depends_on:
      - packages_db
    ports:
      - "8081:8081"
    environment:
      TG_API_TOKEN: 7997289513:AAHM6eRU62wiJmzGxDaTmVlmPVjBiCki2qw
      SPRING_DATASOURCE_URL: jdbc:postgresql://packages_db:5432/packages_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - service

  billing-service:
    build:
      context: ./billing
    restart: always
    depends_on:
      - billing_db
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://billing_db:5432/billing_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - service

networks:
  service:
    driver: bridge
  
volumes:
  packages_data:
  billing_data:
