package ru.hofftech.consolepackages.service.billing;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import ru.hofftech.consolepackages.datastorage.model.entity.OperationType;
import ru.hofftech.consolepackages.datastorage.repository.BillingOrderRepository;
import ru.hofftech.consolepackages.mapper.billing.BillingMapper;
import ru.hofftech.consolepackages.model.Truck;
import ru.hofftech.consolepackages.model.dto.billing.CreatePackageBillRequest;
import ru.hofftech.consolepackages.stream.BillingStreamer;

import java.util.List;

@Slf4j
@RequiredArgsConstructor
public class PackageBillingServiceImpl implements PackageBillingService {

    private final BillingOrderRepository billingOrderRepository;
    private final BillingMapper billingMapper;
    private final BillingStreamer billingStreamer;

    @Override
    public void creatPackageBill(List<Truck> trucks, String clientId, OperationType operationType) {

        billingStreamer.publish(CreatePackageBillRequest.builder()
                .clientId(clientId)
                .operationType(operationType)
                .packageBillDtos(billingMapper.mapTrucksToBillDtos(trucks))
                .requestId(1L) // TODO: add autogenerated by db
                .build());
    }
}
