CREATE TYPE operation_type AS ENUM('LOAD', 'UNLOAD');

CREATE TABLE public.billing_order
(
    id             int8           GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    client_id      varchar        NOT NULL,
    order_date     date           NOT NULL,
    amount         decimal        NOT NULL,
    package_qty    int4           NOT NULL,
    truck_id       uuid           NOT NULL,
    "comment"      varchar        NULL,
    operation_type operation_type NOT NULL,
        CONSTRAINT billing_order_pk PRIMARY KEY (id)
);
COMMENT ON TABLE public.billing_order IS 'Счет по биллингу';