CREATE TABLE public.package_type
(
    id                 int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    form               varchar NOT NULL,
    description_number varchar NOT NULL,
    width              int4    NOT NULL,
    height             int4    NOT NULL,
    CONSTRAINT package_type_pk PRIMARY KEY (id)
);
COMMENT ON TABLE public.package_type IS 'Типы пакетов';
